--
-- PostgreSQL database dump
--

\restrict WNamaXOxEsQl9qkJmSSYA8BCgIsTV8BPMcDp3eOgdtoe7WX6cnYHZKEQcfHofQe

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: advance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advance (
    id bigint NOT NULL,
    number_week integer,
    problem character varying(256),
    send_date timestamp(6) without time zone,
    id_proyect bigint NOT NULL,
    id_student bigint NOT NULL,
    solution character varying(256)
);


ALTER TABLE public.advance OWNER TO postgres;

--
-- Name: advance_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advance_detail (
    id bigint NOT NULL,
    context character varying(256),
    hh double precision,
    type_advance character varying(255) NOT NULL,
    id_advance bigint NOT NULL
);


ALTER TABLE public.advance_detail OWNER TO postgres;

--
-- Name: advance_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advance_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advance_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: advance_future; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advance_future (
    id bigint NOT NULL,
    type_advance character varying(255) NOT NULL,
    id_advance bigint NOT NULL,
    context character varying(256)
);


ALTER TABLE public.advance_future OWNER TO postgres;

--
-- Name: advance_future_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advance_future ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advance_future_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: advance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: helper; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.helper (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    id_teacher bigint
);


ALTER TABLE public.helper OWNER TO postgres;

--
-- Name: helper_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.helper ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.helper_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyect; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyect (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    id_section bigint NOT NULL
);


ALTER TABLE public.proyect OWNER TO postgres;

--
-- Name: proyect_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proyect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: section; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.section (
    id bigint NOT NULL,
    finish_date date,
    is_active boolean,
    section_code character varying(255) NOT NULL,
    semester integer NOT NULL,
    start_date date,
    year integer NOT NULL,
    id_teacher bigint
);


ALTER TABLE public.section OWNER TO postgres;

--
-- Name: section_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    id_section bigint NOT NULL,
    id_proyect bigint
);


ALTER TABLE public.student OWNER TO postgres;

--
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.teacher OWNER TO postgres;

--
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: advance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advance (id, number_week, problem, send_date, id_proyect, id_student, solution) FROM stdin;
2	1	no pudimos juntarnos	2026-05-25 14:32:34.02	2	50	hicimos lo que pudimos, que no fue mucho
3	2	n/r	2026-05-25 14:35:25.351	2	50	n/r
4	3	no me pude levantar	2026-05-25 15:03:22.885	2	50	poner 2 despertadores
5	3	n/r	2026-05-25 15:17:49.259	3	52	n/r
6	4	muuuchos	2026-05-25 15:21:50.781	3	52	nada se pudo hacer
7	9	n/r	2026-05-25 15:44:22.946	3	52	n/r
8	3	no caho ná	2026-05-25 15:46:45.062	3	51	estudiar
9	4	Problemas de acceso a la MV	2026-05-26 15:32:28.995	2	50	Habia realizado cambio de clave por temas de hackeos Universitarios y resulta que la MV no soporta claves con "/" se opto por otra
28	2	Hasta el minuto no se han identificado problemas técnicos.	2026-04-09 12:11:35	14	77	n/r
30	2	n/r	2026-04-09 13:30:40	16	79	n/r
31	2	n/r	2026-04-09 21:00:57	17	80	n/r
32	2	n/r	2026-04-09 22:10:19	16	81	n/r
34	2	No tenemos problemas por ahora	2026-04-11 10:55:37	18	83	n/r
35	2	n/r	2026-04-11 13:03:56	16	84	n/r
36	2	n/r	2026-04-12 03:37:00	18	85	n/r
37	2	No existen	2026-04-12 22:18:43	18	86	n/r
38	2	n/r	2026-04-12 23:29:49	16	87	n/r
44	2	reuniones con el cliente, a no ser que hablemos con unos días de anticipación.	2026-04-13 14:52:43	17	93	n/r
45	2	De momento no entramos en esto,	2026-04-13 15:12:29	17	94	n/r
46	2	Desorden en tareas que hacer, he creadl el jira para disminuir y evitar esta problematica	2026-04-13 15:37:34	17	82	n/r
47	2	n/r	2026-04-13 15:37:46	20	95	n/r
48	2	n/r	2026-04-13 15:40:54	20	96	n/r
49	2	n/r	2026-04-13 15:49:08	20	97	n/r
50	2	Hasta ahora no se presentan problemas técnicos evidentes	2026-04-13 16:03:37	21	98	n/r
51	2	n/r	2026-04-13 18:54:45	20	99	n/r
53	2	La primera reunión con el cliente hubo muy mala señal y se tuvo que solicitar nuevamente una reunión para poder entender mejor su problemática.	2026-04-13 20:18:29	20	101	n/r
54	2	Por ahora no hay problemas técnicos que impidan avanzar con el proyecto.	2026-04-13 21:24:08	14	102	n/r
55	2	n/r	2026-04-13 21:57:09	14	103	n/r
57	2	n/r	2026-04-14 00:29:44	14	105	n/r
58	2	n/r	2026-04-16 15:32:56	21	106	n/r
63	4	Por ahora no hemos tenido problemas	2026-04-20 09:29:40	18	83	n/r
64	3	n/r	2026-04-20 09:30:59	16	84	n/r
65	3	n/r	2026-04-20 09:34:01	16	87	n/r
68	3	Coordinación en Jira, se tuvo que aprender cómo es el flujo de trabajo.	2026-04-20 10:05:46	14	77	n/r
70	3	Ningún problema técnico por ahora.	2026-04-20 10:38:18	14	102	n/r
72	3	n/r	2026-04-20 10:56:47	18	86	n/r
74	3	Quizas nos falto algo de claridad con los flujos con el cliente, pero los solucionaremos mejorando el bpmn y las HU.	2026-04-20 14:38:02	17	94	n/r
75	3	n/r	2026-04-20 15:24:45	14	103	n/r
76	3	n/r	2026-04-20 15:39:04	20	101	n/r
78	3	No los hay	2026-04-20 16:49:21	20	96	n/r
79	3	n/r	2026-04-20 20:41:28	20	99	n/r
80	2	n/r	2026-04-20 21:19:05	18	109	n/r
81	3	n/r	2026-04-20 21:23:06	18	85	n/r
83	3	n/r	2026-04-21 13:02:46	14	105	n/r
84	3	n/r	2026-04-21 14:55:36	17	93	n/r
85	3	Nada en este caso	2026-04-23 21:30:21	17	110	n/r
86	3	n/r	2026-04-23 21:48:57	16	79	n/r
87	3	Ningún problema técnico presente hasta ahora que ofusque nuestra planificación	2026-04-24 20:43:51	21	98	n/r
88	3	n/r	2026-04-26 17:32:54	20	95	n/r
89	4	El cliente no se pudo conectar al sprint 0	2026-04-26 17:34:32	20	95	n/r
91	4	N	2026-04-27 10:42:02	18	86	n/r
92	4	n/r	2026-04-27 12:04:50	20	101	n/r
94	5	No hemos tenido problemas técnicos.	2026-04-27 14:00:38	18	83	n/r
96	4	n/r	2026-04-27 16:12:13	16	87	n/r
97	4	n/r	2026-04-27 20:22:22	18	85	n/r
98	4	n/r	2026-04-27 20:30:19	16	84	n/r
99	4	n/r	2026-04-27 20:34:52	20	99	n/r
100	4	n/r	2026-04-27 21:56:23	16	81	n/r
102	4	n/r	2026-04-28 09:30:58	14	103	n/r
110	5	Problemas en entender la base de datos entregada por el cliente	2026-05-04 15:07:14	20	101	n/r
112	5	Haremos las primeras presentaciones al cliente de los avances del código, por lo que vamos preparados para recibir feedback inicial.	2026-05-04 16:17:46	17	94	n/r
113	5	n/r	2026-05-04 19:25:35	16	87	n/r
114	5	n/r	2026-05-04 20:03:18	16	84	n/r
116	5	Sin problemas técnicos	2026-05-04 20:56:06	18	86	n/r
117	5	n/r	2026-05-04 23:02:56	20	99	n/r
119	5	Por ahora no se tienen problemas técnicos.	2026-05-05 13:12:26	14	102	n/r
120	5	n/r	2026-05-05 18:10:45	18	85	n/r
122	5	n/r	2026-05-05 22:02:19	14	105	n/r
124	6	No tuvimos problemas técnicos.	2026-05-06 20:51:04	18	83	n/r
125	3	n/r	2026-05-07 23:11:05	21	106	n/r
126	4	n/r	2026-05-07 23:13:22	21	106	n/r
127	5	n/r	2026-05-07 23:16:09	21	106	n/r
128	5	n/r	2026-05-08 17:10:58	20	95	n/r
132	6	n/r	2026-05-11 20:17:40	20	99	n/r
133	6	n/r	2026-05-11 20:23:42	18	85	n/r
134	6	El uso del draw.io fue complicado para algo tan grande, el UML se hizo por partes	2026-05-11 20:42:24	18	86	n/r
138	6	n/r	2026-05-12 19:42:42	16	84	n/r
140	6	Por ahora ya se resolvieron las dudas con el cliente y se espera poder avanzar más fluido	2026-05-14 22:51:01	20	101	n/r
142	7	Podrían haber problemas de compatibilidad antes de tener todo en docker	2026-05-18 14:28:28	18	86	n/r
143	3	n/r	2026-05-18 19:08:02	20	97	n/r
145	4	n/r	2026-05-18 19:12:55	20	97	n/r
147	5	n/r	2026-05-18 19:14:23	20	97	n/r
148	10	No se presentaron problemas tecnicos	2026-05-18 19:16:08	20	96	n/r
149	6	n/r	2026-05-18 19:16:25	20	97	n/r
150	7	n/r	2026-05-18 19:18:22	20	97	n/r
151	4	No se presentaron problematicas	2026-05-18 19:24:41	20	96	n/r
152	9	Para la presentación del sprint 0 no se presento el cliente	2026-05-18 19:27:21	20	96	n/r
153	7	No se presentaron problemas tecnicos	2026-05-18 19:29:30	20	96	n/r
154	7	n/r	2026-05-18 19:46:14	16	87	n/r
155	7	n/r	2026-05-18 23:55:02	20	99	n/r
156	7	n/r	2026-05-19 18:02:39	16	84	n/r
158	7	n/r	2026-05-19 20:15:00	20	101	n/r
160	7	n/r	2026-05-25 04:13:50	18	109	n/r
161	8	n/r	2026-05-25 04:15:00	18	109	n/r
162	6	n/r	2026-05-25 04:19:55	18	109	n/r
165	8	Sin problemas técnicos esta semana	2026-05-25 10:40:47	18	86	n/r
167	7	No hemos tenido problemas.	2026-05-25 10:46:49	18	83	n/r
169	9	No hemos tenido problemas.	2026-05-25 10:50:24	18	83	n/r
170	6	No se han tenido problemas técnicos.	2026-05-25 12:00:53	14	102	n/r
171	7	No han existido problemas técnicos.	2026-05-25 12:09:45	14	102	n/r
172	8	n/r	2026-05-25 12:46:41	16	87	n/r
173	8	n/r	2026-05-25 13:21:04	18	85	n/r
174	8	n/r	2026-05-25 16:17:12	20	101	n/r
175	8	n/r	2026-05-25 22:03:07	20	99	n/r
177	8	n/r	2026-05-25 23:39:16	16	84	n/r
178	9	n/r	2026-05-26 00:16:50	16	81	n/r
179	8	n/r	2026-05-26 00:18:28	16	81	n/r
180	7	n/r	2026-05-26 00:20:24	16	81	n/r
183	8	No se han tenido problemas técnicos.	2026-05-26 16:40:40	14	102	n/r
184	8	Probando	2026-06-05 16:27:46.151	2	1	Ver si funciona 
185	4	falta información	2026-06-08 16:08:13.041	3	51	agendamos nuevas reuniones
186	5	n/r	2026-06-08 16:09:56.029	3	51	n/r
187	1	n/r	2026-06-08 17:25:56.278	20	95	n/r
188	6	n/r	2026-06-08 17:28:33.019	20	95	n/r
189	7	n/r	2026-06-08 17:31:29.102	20	95	n/r
190	8	n/r	2026-06-08 17:41:25.709	20	95	n/r
191	9	n/r	2026-06-08 17:47:25.29	20	95	n/r
192	10	n/r	2026-06-08 17:52:03.971	20	95	n/r
193	11	n/r	2026-06-08 17:54:53.489	20	95	n/r
194	1	Hubo problemas de conexión en la primera reunión	2026-06-08 18:09:21.095	20	101	se agendó otra reunión
195	10	n/r	2026-06-08 18:15:47.895	20	101	n/r
196	9	n/r	2026-06-08 18:18:28.903	20	101	n/r
197	1	n/r	2026-06-10 01:35:02.252	17	80	n/r
198	9	n/r	2026-06-15 21:50:22.81	20	99	n/r
199	10	n/r	2026-06-15 23:18:50.605	20	99	n/r
200	11	n/r	2026-06-15 23:30:58.065	20	99	n/r
\.


--
-- Data for Name: advance_detail; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advance_detail (id, context, hh, type_advance, id_advance) FROM stdin;
4	cas.msa.c sa;lasc aspdasd 	5	Coordinacion/Planificacion	2
5	nos reunimos 2 veces	4	Reuniones con cliente	2
6	hice lo que pude, que no fue mucho	2	Diseño/Desarrollo de Software	2
7	ASasASasASC alkihLAK aoij	3	Coordinacion/Planificacion	3
8	jasvaj akiqwh qoiwdyqowid	1	Reuniones con cliente	3
9	dsflsj;daslkd a;sdk	4	Diseño/Desarrollo de Software	3
10	mas coord	2	Coordinacion/Planificacion	4
11	construccion modulos	6	Diseño/Desarrollo de Software	4
12	pruebas y pruebas	2	Pruebas/QA	4
13	y atambien documentaciones	4	Documentacion	4
14	coordinaciones...	2	Coordinacion/Planificacion	5
15	una reunion	2	Reuniones con cliente	5
16	habilitacion ambiente	3	Instalaciones/Despliegue	5
17	casi nada	1	Coordinacion/Planificacion	6
18	3 reuniones	4	Reuniones con cliente	6
19	y mucho mas desarrollo	5	Diseño/Desarrollo de Software	6
20	un poquito de documentacipon	1	Documentacion	6
21	y seguimos....	1	Coordinacion/Planificacion	7
22	buena conversa	2	Reuniones con cliente	7
23	y mas desarrollo....	4	Diseño/Desarrollo de Software	7
24	nos reunimos	2	Reuniones con cliente	8
25	preparar ambientes	2	Instalaciones/Despliegue	8
26	Prueba de ingreso de medias horas en HH	3.5	Diseño/Desarrollo de Software	9
27	Se desplego la plataforma de Seguimiento semanal	2	Instalaciones/Despliegue	9
104	Entrevista con clientes, recopilación datos y organización en jira.	3	Coordinacion/Planificacion	28
105	Entendimiento inicial de negocio y que buscan obtener.	1.5	Reuniones con cliente	28
106	Todavía no empieza el desarrollo.	0	Diseño/Desarrollo de Software	28
107	Todavía no empieza el desarrollo.	0	Instalaciones/Despliegue	28
108	Todavía no empieza el desarrollo.	0	Pruebas/QA	28
109	Todavía no empieza el desarrollo.	0	Documentacion	28
110	Todavía no empieza el desarrollo.	0	Entrega/Capacitacion	28
111	Todavía no empieza el desarrollo.	0	Otros	28
627	nos reunimos con todo el equipo	1	Coordinacion/Planificacion	185
628	preparando el diseño	4	Diseño/Desarrollo de Software	185
114	Proposición de la separación de roles, organización de tareas y org general	3	Coordinacion/Planificacion	30
115	Dirección de la reunión, captura de requerimientos	1	Reuniones con cliente	30
116	Organización de presentación.	1	Coordinacion/Planificacion	31
117	Preguntas relacionadas al futuro del proyecto y a su arquitectura.	2	Reuniones con cliente	31
118	Identificación de datos utilizados por cliente para posterior diseño de arquitectura.	1	Otros	31
119	Logramos coordinar y planificar reuniones para trabajar en conjunto	2	Coordinacion/Planificacion	32
120	Conocimos al cliente, su problemática y logramos capturar los requerimientos	1	Reuniones con cliente	32
121	Completamos la minuta 1, requerimientos HU y la transcripción de la reunión 1	2	Documentacion	32
629	reunion de coord semanal	1	Coordinacion/Planificacion	186
630	cominzo a trabajar en CRUD del backend	3	Diseño/Desarrollo de Software	186
649	Se coordinaron las vistas a implementar en el frontend	1	Coordinacion/Planificacion	196
125	Organicé el flujo con el cliente y los próximos hitos a realizar	4	Coordinacion/Planificacion	34
126	Revisamos el flujo que lleva la empresa hoy en día y lo que esperan	2	Reuniones con cliente	34
127	Levantamiento de requerimientos en la reunion con cliente	1	Diseño/Desarrollo de Software	34
128	No lo hemos empezado	0	Instalaciones/Despliegue	34
129	No lo hemos empezado	0	Pruebas/QA	34
130	Minutas de reunión	1	Documentacion	34
131	No lo hemos empezado	0	Entrega/Capacitacion	34
132	Primer diagrama de arquitectura y uml inicial	3	Otros	34
133	Coordine la hora y el día para realizar una reunión con el equipo	1	Coordinacion/Planificacion	35
134	Preguntar respecto al material grafico que manejan.	0.6	Reuniones con cliente	35
135	Redacte el contenido de la minuta de la primera reunión con el cliente	2	Documentacion	35
136	Reunión de equipo para organizar la semana siguiente, reunión presencial	0.5	Coordinacion/Planificacion	36
137	Reunión presencial en la pastelería, conocer a fondo la empresa y sus problemas	2	Reuniones con cliente	36
138	Se coordinaron reuniones y se planifico la semana y cree las minutas	3	Coordinacion/Planificacion	37
139	Dos reuniones de 1 hora, se aclararon dudas iniciales y pipeline de productos	2	Reuniones con cliente	37
140	Ayudé en la planifcación y realización de preguntas y temas  para la clienta.	1.45	Reuniones con cliente	38
141	Ayudé a documentar la organizacion del equipo, la minuta y las HU.	2.3	Documentacion	38
142	Actuar como punto de contacto principal con el cliente como PO	0.5	Otros	38
650	se hicieron correcciones al mockup, se implementó el inicio de sesión y la gestión de usuarios	4	Diseño/Desarrollo de Software	196
631	Elaboracion inicial de los primeros hitos a cumplir	1	Coordinacion/Planificacion	187
632	Conocer al cliente y entender su problematica	2	Reuniones con cliente	187
651	Investigación sobre problemática de cliente. Definición de propuestas.	2	Coordinacion/Planificacion	197
170	Separación de roles, organización de reunión entre el equipo.	2	Coordinacion/Planificacion	44
171	prestar atención a lo que dice y hacer preguntas.	1	Reuniones con cliente	44
172	Organice la reunión con el cliente, y cree un mockup inicial.	3	Coordinacion/Planificacion	45
173	Recopilamos información inicial y requerimientos a implementar.	1	Reuniones con cliente	45
174	Creamos un mockup inicial en código.	0	Diseño/Desarrollo de Software	45
175	Solo investigamos un poco, aun no trabajamos en esto.	0	Instalaciones/Despliegue	45
176	Aun no trabajamos en esto.	0	Pruebas/QA	45
177	Recopilamos la minuta inicial.	1	Documentacion	45
178	Le enviamos el diseño, y recibimos una plantilla de su estructura.	1	Entrega/Capacitacion	45
179	Organización de próximas entregas.	1	Otros	45
180	Creación de historias de usuario, requerimientos funcionales y no (f), alcance	3	Coordinacion/Planificacion	46
181	0	0	Instalaciones/Despliegue	46
182	Minuta, historias de usuario, requerimientos, reunión transcrita y editada	3	Documentacion	46
183	Creación de jira para organizar el equipo	1	Otros	46
184	Coordinacion de reuniones, planificacion de fechas y definicion de preguntas	2	Coordinacion/Planificacion	47
185	Coordinacion de la comunicacion cliente - equipo	2	Reuniones con cliente	47
186	Definicion de epicas e historias de usuarios y establecimiento de carta gantt	2	Documentacion	47
187	Ayude al equipo a coordinar las reuniones entre el equipo y el cliente	0.5	Coordinacion/Planificacion	48
188	Hablamos del flujo actual que maneja y se le hicieron preguntas al respecto	2	Reuniones con cliente	48
189	Se formalizo el documento de requerimientos del proyecto.	1.5	Documentacion	48
190	Organización de la reunión con el cliente, junto a todo el grupo.	0.5	Coordinacion/Planificacion	49
191	Tomé el rol de secretario, sinteticé lo discutido en la reunión.	2	Reuniones con cliente	49
192	Documento de alcances y limitaciones.	1	Documentacion	49
193	Planificar la junta de la proxima semana, formato entrevistas y asignar roles	4	Coordinacion/Planificacion	50
194	obtuvo los problemas, lo que el cliente quiere, desea y busca priorizar	1	Reuniones con cliente	50
195	Se preparó el ppt de la presentación, preparación del sprint 0.	3	Otros	50
196	Planteo de preguntas para primera reunión en relación al problema	1	Coordinacion/Planificacion	51
197	Entender problema y necesidades	2	Reuniones con cliente	51
198	Registrar primera versión de requerimientos funcionales y no funcionales	2	Documentacion	51
207	Coordiné al grupo previamente a la reunión con el cliente.	4	Coordinacion/Planificacion	53
208	Se entendió la problemática y las necesidades del cliente	2.5	Reuniones con cliente	53
209	Hice el material de presentación de Sprint Weekly #1 con mi grupo de trabajo.	2	Coordinacion/Planificacion	54
210	Reuní requerimientos funcionales y no funcionales para la página web.	2	Reuniones con cliente	54
211	Se hará a futuro. Estamos en el proceso de planificación del proyecto.	0	Diseño/Desarrollo de Software	54
212	No se ha hecho nada en este punto aún. Se hará en un futuro.	0	Instalaciones/Despliegue	54
213	No se ha hecho nada en este punto aún. Se hará en un futuro.	0	Pruebas/QA	54
214	No se ha hecho nada en este punto aún. Se hará a futuro.	0	Documentacion	54
215	El proyecto está comenzando aún, por lo que no hay entrega de nada aún.	0	Entrega/Capacitacion	54
216	Logré dar ideas para el proximo Sprint como el diagrama de caso de uso e historia de usuario.	0	Otros	54
217	Se concretó una reunión con todo el grupo de trabajo	2	Coordinacion/Planificacion	55
218	Hubo un primer acercamiento al cliente, se conoció más sobre su negocio	2	Reuniones con cliente	55
219	Investigué sobre el público objetivo al que busca llegar el cliente	1	Otros	55
633	Desarrollo inicial del sistema. Inicializacion de los entornos y sistemas de verificacion.	3	Diseño/Desarrollo de Software	188
652	- Preparar presentación de sprint 1.	3	Coordinacion/Planificacion	198
653	- Crear CRUD de configuración base.\n- Conectar configuración base en frontend.\n- Ajustar visualización del PDF de una cotización en frontend.	6	Diseño/Desarrollo de Software	198
223	Overview del proyecto, plan de sprint 0.	5	Coordinacion/Planificacion	57
224	Registro del funcionamiento y visión del negocio.	2	Reuniones con cliente	57
225	Se tuvo el primer acercamiento con el cliente, se escucharon sus problemas.	0	Reuniones con cliente	58
226	se vieron los videos que habían de documentación, y además se analizo la pagina.	3	Diseño/Desarrollo de Software	58
227	se tomó nota de toda información sobre la página que ya existe.	1	Documentacion	58
228	Se converso con el usuario anterior que trabajo en la página, obteniendo información relevante	1	Otros	58
241	organice las reuniones y que hacer en las reuniones	1	Coordinacion/Planificacion	63
242	solicitamos informacion relevante a la clienta	0	Reuniones con cliente	63
243	levantamos requerimientos funcionales y no funcionales	0	Diseño/Desarrollo de Software	63
244	no se realizó	0	Instalaciones/Despliegue	63
245	no se realizó	0	Pruebas/QA	63
246	avancé el documento de requerimientos	1	Documentacion	63
247	no se realizó	0	Entrega/Capacitacion	63
248	Avances en diagramas.	0	Otros	63
249	Presentar alcances y limitaciones	1	Reuniones con cliente	64
250	Reescribir y evaluar las HU, donde se eliminaron 2 y se agregaron 2 nuevas	2	Documentacion	64
251	Horas Esfuerzo, Horas Hombre	2	Coordinacion/Planificacion	65
252	Definir alcances y limitraciones	1.5	Reuniones con cliente	65
268	Validación de HU y definición por documento de alcances. Inicio de diseño sw.	2	Coordinacion/Planificacion	68
269	Entendimiento y bosquejo de sistema. Definición en piedra de alcances.	2	Reuniones con cliente	68
270	Todavía no empezamos a desarrollar.	0	Diseño/Desarrollo de Software	68
271	Todavía no es pertinente despliegue.	0	Instalaciones/Despliegue	68
272	Todavía no empieza proceso de QA.	0	Pruebas/QA	68
273	Todavía no empieza proceso de documentación.	0	Documentacion	68
274	Todavía no se entrega.	0	Entrega/Capacitacion	68
275	Todo va de acuerdo a planificación.	0	Otros	68
634	Control de roles e implementacion de autenticacion JWT.	3	Diseño/Desarrollo de Software	189
635	Muestra de avances y dudas tecnicas de cotizacion	1	Reuniones con cliente	189
654	- Reformular para manejar información de PDF y empresa, y ajustar CRUD asociado.\n- Integrar CRUD para información de PDF, pagos, métodos de pago y elementos adicionales.\n- Crear documento sql base.\n- Actualizar conexiones en frontend.	20	Diseño/Desarrollo de Software	199
655	- Reuniones de grupo para resolver dudas de funcionamiento y corrección de errores.	4	Coordinacion/Planificacion	199
282	Ningún logro.	0	Coordinacion/Planificacion	70
283	Obtuve información importante para realizar los RF Y RNF.	2	Reuniones con cliente	70
284	Recolección de RF, RNF e Historias de Usuario para el proyecto. .	3	Diseño/Desarrollo de Software	70
285	Ningún logro.	0	Instalaciones/Despliegue	70
286	Ningún logro.	0	Pruebas/QA	70
287	Ningún logro.	0	Documentacion	70
288	Ningún logro.	0	Entrega/Capacitacion	70
289	Ningún logro.	0	Otros	70
293	n/r	2	Coordinacion/Planificacion	72
294	Se hicieron los RF divididos en funcionalidades más grandes	0	Diseño/Desarrollo de Software	72
298	Coordinamos entregables varios para el spring 0 y reunión con cliente.	5	Coordinacion/Planificacion	74
299	Establecimos limites y alcances y mas funcionalidades a implementar.	2	Reuniones con cliente	74
300	Aun no desarrollaremos software.	0	Diseño/Desarrollo de Software	74
301	Aun no nos dedicamos a estas tareas.	0	Instalaciones/Despliegue	74
302	Aun no nos dedicamos a estas tareas.	0	Pruebas/QA	74
303	Realizamos la documentación de varias cosas.	4	Documentacion	74
304	Entregamos documentación como bpmn, mr y HU iniciales.	2	Entrega/Capacitacion	74
305	ya he descrito las actividades en lo anterior.	0	Otros	74
306	Se planifican las tareas que realizar para el avance semanal	1	Coordinacion/Planificacion	75
307	Se aclaran dudas sobre alcances y límites	2	Reuniones con cliente	75
308	Se planificaron las reuniones y se ayudó a coordinar la reunión con el cliente	3	Coordinacion/Planificacion	76
309	Se validaron documentos con el cliente, como los alcances, requerimientos, etc	2	Reuniones con cliente	76
313	Concrete diferentes reunion, para tareas, con el equipo y el cliente	0.5	Coordinacion/Planificacion	78
314	Logramos validar requerimientos, carta gantt, alcances, entre otros.	1	Reuniones con cliente	78
315	Se concretaron los requerimientos y presentaciones.	1	Documentacion	78
316	Apoyar en preparar reunión online y presencial con el cliente.	3	Coordinacion/Planificacion	79
317	Validar avances	2	Reuniones con cliente	79
318	Revisar y corregir requerimientos	2	Documentacion	79
319	Se logró el propósito de entender la problemática	3	Coordinacion/Planificacion	80
320	Se logró el propósito de entender la problemática	3	Reuniones con cliente	80
321	coordinar reunión equipo, desarrollo requerimientos, edt + esfuerzo, ppt.	2	Coordinacion/Planificacion	81
330	coordinar reunión cliente, y entre el equipo	2	Coordinacion/Planificacion	83
331	primera validación de HUs, alcances y limitaciones.	2	Reuniones con cliente	83
332	avances en documentos de diseño	1	Documentacion	83
333	Realización del ppt, formulación de HU	5	Coordinacion/Planificacion	84
334	Explicar información importante al cliente sobre metodología de trabajo	2	Reuniones con cliente	85
335	Cotizaciones y minuta de la reunión	3	Documentacion	85
336	Asignar tareas en jira y dividir trabajo	2	Coordinacion/Planificacion	86
337	Se definieron alcances y limitaciones	1	Reuniones con cliente	86
338	Alcances y limitaciones, minutas	2	Documentacion	86
339	Coordinar horarios de entrevista, preguntas y diagramas que se presentaron	6	Coordinacion/Planificacion	87
340	Consólidaron alcances y limitaciones	1	Reuniones con cliente	87
341	Se logro planificar las reuniones semanales como equipo	1	Coordinacion/Planificacion	88
342	Validar los artefactos de la solucion con el cliente	2	Reuniones con cliente	88
343	Completar la carta Gantt y el desgloce de las epicas	1	Documentacion	88
344	Se lograron realizar las reuniones de coordinacion	1	Coordinacion/Planificacion	89
345	Termino de la carta Gantt y desgloce de epicas	2	Documentacion	89
636	Muestra de avances y desicion de hosting del proyecto	1	Reuniones con cliente	190
637	Validacion y pruebas de API 	1	Pruebas/QA	190
656	- Participar en reunión donde se presentaron avances, se resolvieron dudas y se recibió retroalimentación.	1	Reuniones con cliente	200
657	- Se revisó como abordar correcciones necesarias y repartir tareas.	2	Coordinacion/Planificacion	200
658	- Desarrollar CRUDs faltantes.\n- Integrar una primera versión del impacto de eliminar información de las bases.\n- Integrar conexiones en frontend para gestionar las bases de precios.	10	Diseño/Desarrollo de Software	200
354	Se planificó la presentación y afinaron los detalles de la planeación	1	Coordinacion/Planificacion	91
355	Se aclaró lo de la API de deFontana	1	Reuniones con cliente	91
356	Coordiné y ayudé a organizar la presentación del sprint 0	2	Coordinacion/Planificacion	92
357	Presentación del sprint 0	1	Reuniones con cliente	92
358	Se documentó una propuesta de metricas de calidad	3	Documentacion	92
367	Logramos coordinar al máximo las proximas entregas.	2	Coordinacion/Planificacion	94
368	Se solicitó a Mónica que pudiese estandarizar los nombres de los productos	2	Reuniones con cliente	94
369	0	0	Pruebas/QA	94
370	Historias de usuario, presentación.	2	Documentacion	94
371	0	0	Entrega/Capacitacion	94
376	Planifiqué los próximos pasos y la planificación general	1	Coordinacion/Planificacion	96
377	Ser mediador con la clienta	1	Reuniones con cliente	96
378	Construcción documentos, reunión zoom y presencial, finalizar sprint 0.	2	Coordinacion/Planificacion	97
379	Validación sprint 0 con cliente, visita presencial y zoom, compromiso documentos	3	Reuniones con cliente	97
380	Se comenzo el diseño del MER y MR	1	Diseño/Desarrollo de Software	98
381	Preparacion para la entrega del spring 0	2	Documentacion	98
382	Participar en planificar presentación de sprint 0	2	Coordinacion/Planificacion	99
383	Construir el BPMN	3	Documentacion	99
384	Pasarelas de pago y diapositvas Sprint Review	3	Documentacion	100
386	Se organiza lo que cada participante debe decir en la presentación	1	Coordinacion/Planificacion	102
387	Se completa el diagrama de casos de uso y se hace el ppt para la presentación	2	Documentacion	102
638	Presentacion Sprint 1 	2	Reuniones con cliente	191
639	Preparacion de presentacion de avances y reportes de tareas	2	Documentacion	191
409	Reuniones con equipo fullstack para definir vistas y revisar mockup	2	Coordinacion/Planificacion	110
410	Se definieron las vistas y se comenzó con el desarrollo del mockup	9	Diseño/Desarrollo de Software	110
412	Hemos coordinado los primeros avances de codigo y primera entrega.	3	Coordinacion/Planificacion	112
413	No tuvimos reunion, solo spring 0 donde le hemos presentado.	0	Reuniones con cliente	112
414	Creamos template inicial de frontend y backend con crud.	6	Diseño/Desarrollo de Software	112
415	Aun no corresponden estas tareas.	0	Instalaciones/Despliegue	112
416	Aun no corresponden estas tareas.	0	Pruebas/QA	112
417	Hemos organizado la documentación para entregar el sprint 0.	1	Documentacion	112
418	Hemos entregado el sprint 0 al cliente.	4	Entrega/Capacitacion	112
419	Esta todo concentrado en las otras actividades.	0	Otros	112
420	apoyo en finalizar el MER MR	1	Diseño/Desarrollo de Software	113
421	Terminar diseño preliminar de MER y MR	1.5	Diseño/Desarrollo de Software	114
430	Se pudo coordinar las tareas de cada uno en el desglose de las actividades	1	Coordinacion/Planificacion	116
431	Reunión con encargado de frontend	1	Coordinacion/Planificacion	117
432	Apoyo en definición de vistas y construcción de modelo de base de datos	7	Diseño/Desarrollo de Software	117
434	No se coordino nada.	0	Coordinacion/Planificacion	119
435	No nos reunimos con el cliente. Lo vamos a hacer pronto.	0	Reuniones con cliente	119
436	Se hizo diseño del Mockup para la página web de Mundo Neurodiferente.	3	Diseño/Desarrollo de Software	119
437	No se ha hecho despliegue.	0	Instalaciones/Despliegue	119
438	No se ha hecho QA.	0	Pruebas/QA	119
439	No se ha hecho ninguna documentación por ahora.	0	Documentacion	119
440	No se ha hecho entregas.	0	Entrega/Capacitacion	119
441	No se han hecho otras actividades aún.	0	Otros	119
442	organizar actividades de la semana	1	Coordinacion/Planificacion	120
445	Planificar actividades siguiente semana	2	Coordinacion/Planificacion	122
446	Mockup inicial del producto	3	Diseño/Desarrollo de Software	122
450	principalmente coordinar al equipo y designar tareas por persona.	3	Coordinacion/Planificacion	124
451	diagramas de arquitectura y además la mejora en las ppts que se utilizarán	2.5	Documentacion	124
452	Se logro coordinar las reuniones con el cliente	4	Coordinacion/Planificacion	125
453	Se lograron zanjar varias ideas que se tenian con el cliente	1	Reuniones con cliente	125
454	Se tuvieron las primeras ideas del desarrollo de la pagina	1	Diseño/Desarrollo de Software	125
455	Se describieron todos los datos que se desarrollaron y las reuniones con cliente	1	Documentacion	125
456	Cada vez estan más consolidadas las reuniones con el equipo	1	Coordinacion/Planificacion	126
457	Ahora se sabe que días vamos a tener reuniones y las necesidades que tienen	1	Reuniones con cliente	126
458	Se analizo con más profundidad la pagina	1	Diseño/Desarrollo de Software	126
459	Se registraron todos los nuevos contenidos descubiertos.	1	Documentacion	126
460	Se aprendio con más detalle el funcionamiento de los plugin que los chiquillos anteriores usaron para la pagina	1	Otros	126
461	Como grupos hicimos reuniones para hacer presentaciones y delegar tareas	1	Coordinacion/Planificacion	127
462	Hice preguntas y mostré avances de la página web	1	Reuniones con cliente	127
463	Estuve viendo el funcionamiento del catalogo que había implementado.	2	Diseño/Desarrollo de Software	127
464	Estuve un buen rato investigando como funcionan las cosas, como diseños y herramientas.	1	Otros	127
465	Diseño logico de la base de datos de la solucion	4	Diseño/Desarrollo de Software	128
466	Se documentaron los avances en la carta Gannt	1	Documentacion	128
640	Dudas tecnicas sobre numeros y formulas en las cotizaciones	1	Reuniones con cliente	192
641	Desarrollo de logica de las cotizaciones	4	Diseño/Desarrollo de Software	192
642	Muestra de avances y dudas tecnicas	2	Reuniones con cliente	193
643	Desarrollo de logica de cotizaciones, flujos y filtros para el CRUD basico de cada modelo	4	Diseño/Desarrollo de Software	193
644	Validacion de funciones desarrolladas	1	Pruebas/QA	193
477	Preparar presentación	1	Coordinacion/Planificacion	132
478	Se resolvieron dudas de lógica	1	Reuniones con cliente	132
479	Aplicar correcciones, a partir de dudas resueltas, en el modelo de base de datos	0.5	Diseño/Desarrollo de Software	132
480	creación MER, planificación reuniones equipo, jira	2	Coordinacion/Planificacion	133
481	Se diseñaron los métodos y se organizaron en un UML	3	Diseño/Desarrollo de Software	134
499	Inicializacion del FrontEnd	2	Diseño/Desarrollo de Software	138
501	coordinar preguntas para el cliente	2	Coordinacion/Planificacion	140
502	resolver consultas con respecto a la base de datos	2	Reuniones con cliente	140
505	Se diseñaron algunas vistas del frontend y se inició el proyecto en nuxt	3	Diseño/Desarrollo de Software	142
506	Coordinación de entrevista con el cliente.	0.5	Coordinacion/Planificacion	143
507	Mayor entendiemiento del sistema.	1	Reuniones con cliente	143
508	Redacción de alcances y limitaciones.	2	Documentacion	143
512	Preparación de presentación.	2	Coordinacion/Planificacion	145
513	Arreglos a documentación.	2	Documentacion	145
515	Diseño de la base de datos.	5	Diseño/Desarrollo de Software	147
516	Me cordine con mi equipo para la realización de actividades	1	Coordinacion/Planificacion	148
517	Se aclararon dudas con el cliente con respecto al funcionamiento del excel	1	Reuniones con cliente	148
518	Diseñe el modelo relacional de la base de datos	5	Diseño/Desarrollo de Software	148
519	Coordinación reunión con cliente y presentación.	2.5	Coordinacion/Planificacion	149
520	Validación de avances.	1	Reuniones con cliente	149
521	Cambios al diseño de la base de datos.	0.5	Diseño/Desarrollo de Software	149
522	Diseño de la lógica del sistema de creación de cotizaciones.	5	Diseño/Desarrollo de Software	150
523	Me coordine con mi grupo de trabajo para la realización de tareas	3	Coordinacion/Planificacion	151
524	Resolvimos dudas con el	0	Reuniones con cliente	151
525	Realize el diagrama de arquitectura	1	Diseño/Desarrollo de Software	151
590	Desarollo vistas Frontend	0.4	Diseño/Desarrollo de Software	173
526	Me coordine con mi equipo para la realización de actividades	1	Coordinacion/Planificacion	152
527	Aclaramos dudas con respecto al funcionamiento del excel	1	Reuniones con cliente	152
528	Realize el modelado de la base de datos	5	Diseño/Desarrollo de Software	152
529	Me coordine con mi quipo para la realización de actividades	1	Coordinacion/Planificacion	153
530	Inicialize los repositorios y configure el backend del proyecto	5	Diseño/Desarrollo de Software	153
531	Determinar Hosting, pasarelas de pago y formato de compra del cliente	1.3	Reuniones con cliente	154
532	Catalogo, vista general y secundarias y arreglo UX/UI	3	Diseño/Desarrollo de Software	154
533	Apoyar en creación de mockup	2	Diseño/Desarrollo de Software	155
534	Se realizaron pruebas del modulo de usuarios	1	Pruebas/QA	155
535	Desarrollo de componente whatsapp y vista principal	4	Diseño/Desarrollo de Software	156
645	Se coordinó al equipo y se planificó como abordar la primera reunión con el cliente	4	Coordinacion/Planificacion	194
646	se tuvieron dos reuniones para entender el negocio del cliente	4	Reuniones con cliente	194
544	Se logró planificar y coordinar el desarrollo del mockup	2	Coordinacion/Planificacion	158
545	Se completaron las vistas necesarias para el proyecto en el mockup	9	Diseño/Desarrollo de Software	158
549	Se redefine las HH del sprint 0 para ser considerada en la EDT. Además otros.	6	Coordinacion/Planificacion	160
550	Planificación principalmente del backend y del frontend.	3	Diseño/Desarrollo de Software	160
551	Practicamente termino el frontend completo junto con avance en el backend	42	Diseño/Desarrollo de Software	161
552	Retroalimentación del sprint0 y reasignación de puntos de historia, equivalencia	7	Coordinacion/Planificacion	162
555	Diseño de más vistas en el frontend y creación de componentes reutilizables	4	Diseño/Desarrollo de Software	165
559	principalmente me dediqué a organizar al equipo y además coordinar con mónica	1	Coordinacion/Planificacion	167
560	principalmente la versión final del diagrama de arquitectura y tabla de costos	3	Documentacion	167
561	0	0	Entrega/Capacitacion	167
565	principalmente me dediqué a organizar al equipo y ver reportes de avance.	2	Coordinacion/Planificacion	169
566	0	0	Reuniones con cliente	169
567	crud de los modulos del sprint 1 y logica del negocio, faltante QA.	10	Diseño/Desarrollo de Software	169
568	no aplica.	0	Instalaciones/Despliegue	169
569	no aplica.	0	Pruebas/QA	169
570	documentacion basada en el código implementado.	1	Documentacion	169
571	no aplica.	0	Entrega/Capacitacion	169
572	no aplica.	0	Otros	169
573	No hubo nada esta semana.	0	Coordinacion/Planificacion	170
574	No hubo reuniones con cliente	0	Reuniones con cliente	170
575	Hice parte del diseño general (frontend) de la web a través de Figma.	2	Diseño/Desarrollo de Software	170
576	No se realizó despliegue	0	Instalaciones/Despliegue	170
577	No se hizo pruebas/QA.	0	Pruebas/QA	170
578	No se ha hecho documentación.	0	Documentacion	170
579	No se hizo entrega.	0	Entrega/Capacitacion	170
580	No hubo logros en actividades en esta semana.	0	Otros	170
581	No hice actividades en este aspecto.	0	Coordinacion/Planificacion	171
582	No se tuvo reunión con cliente.	0	Reuniones con cliente	171
583	Hice parte del diseño responsivo de la página web en frontend.	3	Diseño/Desarrollo de Software	171
584	No hice actividades en este aspecto	0	Instalaciones/Despliegue	171
585	No hice actividades en este aspecto.	0	Pruebas/QA	171
586	No hice actividades en este aspecto.	0	Documentacion	171
587	No hice actividades en este aspecto	0	Entrega/Capacitacion	171
588	No hice actividades en este aspecto.	0	Otros	171
589	Frontend: Vistas de Carrito, producto, y arreglo vista general y catalogos	3	Diseño/Desarrollo de Software	172
591	Se organizaron reuniones para organizar el equipo	1	Coordinacion/Planificacion	174
592	Se validó el mockup y se resolvieron dudas de las bases	2	Reuniones con cliente	174
593	Se terminó el mockup	7	Diseño/Desarrollo de Software	174
594	Preparar reporte de avance	2	Coordinacion/Planificacion	175
595	Validar mockup y resolver dudas en relación a las bases	1	Reuniones con cliente	175
596	Documentar minuta de reunión	0.5	Documentacion	175
647	Se planificó y coordinó la presentación del sprint 1	3	Coordinacion/Planificacion	195
598	Desarrollo vista catalogo por categoria	3	Diseño/Desarrollo de Software	177
599	Preparamos la Weekly 5	2	Coordinacion/Planificacion	178
600	Implementacion de CRUDS restantes y cambios en dockerfile	6	Diseño/Desarrollo de Software	178
601	CRUD Cliente, Direccion	4	Diseño/Desarrollo de Software	179
602	Test unitarios para Cliente y direccion	1	Pruebas/QA	179
603	Presentacion pasarelas de pago	2	Reuniones con cliente	180
604	Implementacion del CRUD del Carrito	3	Diseño/Desarrollo de Software	180
605	Investigacion sobre Hostings	2	Documentacion	180
648	Se presentó el sprint 1 al cliente	1	Reuniones con cliente	195
617	No hice actividades en este aspecto.	0	Coordinacion/Planificacion	183
618	No hice actividades en este aspecto.	0	Reuniones con cliente	183
619	Empece a hacer el CRUD del Producto para el catálogo en backend.	3	Diseño/Desarrollo de Software	183
620	No hice actividades en este aspecto.	0	Instalaciones/Despliegue	183
621	No hice actividades en este aspecto.	0	Pruebas/QA	183
622	No hice actividades en este aspecto.	0	Documentacion	183
623	No hice actividades en este aspecto.	0	Entrega/Capacitacion	183
624	No hice actividades en este aspecto.	0	Otros	183
625	Muchas cosas	25	Coordinacion/Planificacion	184
626	Validando funcionamiento	2	Reuniones con cliente	184
\.


--
-- Data for Name: advance_future; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advance_future (id, type_advance, id_advance, context) FROM stdin;
71	Coordinacion/Planificacion	28	n/r
72	Reuniones con cliente	28	n/r
73	Diseño/Desarrollo de Software	28	n/r
421	Diseño/Desarrollo de Software	185	comenzaré a desarrollar la parte que me toca
5	Coordinacion/Planificacion	2	programamos 1 reunion de coordinacion por meet
6	Reuniones con cliente	2	nos juntaremos 1 vez la proxima semana
7	Diseño/Desarrollo de Software	2	ahora si que hare un buen diseño
8	Instalaciones/Despliegue	2	habilitare el ambiuente en mi PC
9	Entrega/Capacitacion	3	ASDASD;LASK'; AS[PDIA[[psir[fp we[wev
10	Documentacion	3	frefpi se0iwe0r 
11	Reuniones con cliente	4	una nueva reunion
12	Diseño/Desarrollo de Software	4	seguir desarrollando el mismo modulo
13	Coordinacion/Planificacion	5	y mas coordinacion
14	Diseño/Desarrollo de Software	5	seguir diseñando y construyendo
15	Documentacion	5	algo se documentará...
16	Diseño/Desarrollo de Software	6	seguir desarrollando
17	Documentacion	6	seguir documentando
18	Diseño/Desarrollo de Software	7	solo trabajar....
19	Coordinacion/Planificacion	8	mas reuniones
20	Diseño/Desarrollo de Software	8	comenzar a desarrollar
21	Reuniones con cliente	9	Validacion de la actualziacion de la plataforma de seguimiento de pingeso
22	Pruebas/QA	9	El profesor realizara probas para ver si esta satisfecho con el resultado la plataforma
422	Diseño/Desarrollo de Software	186	seguiré desarrollando en el backend
76	Coordinacion/Planificacion	30	n/r
77	Reuniones con cliente	30	n/r
78	Diseño/Desarrollo de Software	30	n/r
79	Documentacion	30	n/r
80	Coordinacion/Planificacion	31	n/r
81	Reuniones con cliente	31	n/r
82	Diseño/Desarrollo de Software	31	n/r
83	Coordinacion/Planificacion	32	n/r
84	Diseño/Desarrollo de Software	32	n/r
85	Documentacion	32	n/r
429	Documentacion	190	Desarrollo de presentaciones de avance y reporte de tareas 
430	Diseño/Desarrollo de Software	190	Integracion entre Backend y Frontend
88	Coordinacion/Planificacion	34	n/r
89	Reuniones con cliente	34	n/r
90	Diseño/Desarrollo de Software	34	n/r
91	Documentacion	34	n/r
92	Diseño/Desarrollo de Software	35	n/r
93	Coordinacion/Planificacion	36	n/r
94	Diseño/Desarrollo de Software	36	n/r
95	Coordinacion/Planificacion	37	n/r
96	Coordinacion/Planificacion	38	n/r
97	Reuniones con cliente	38	n/r
442	Coordinacion/Planificacion	195	Coordinar como continuar y qué tareas realizar
443	Diseño/Desarrollo de Software	195	Continuar implementando el backend al frontend
449	Reuniones con cliente	199	Presentar avances y resolver dudas.
450	Diseño/Desarrollo de Software	199	Continuar desarrollo de las bases.
113	Coordinacion/Planificacion	44	n/r
114	Diseño/Desarrollo de Software	44	n/r
115	Coordinacion/Planificacion	45	n/r
116	Reuniones con cliente	45	n/r
117	Diseño/Desarrollo de Software	45	n/r
118	Documentacion	45	n/r
119	Coordinacion/Planificacion	46	n/r
120	Documentacion	46	n/r
121	Coordinacion/Planificacion	47	n/r
122	Reuniones con cliente	47	n/r
123	Documentacion	47	n/r
124	Coordinacion/Planificacion	48	n/r
125	Reuniones con cliente	48	n/r
126	Documentacion	48	n/r
127	Reuniones con cliente	49	n/r
128	Documentacion	49	n/r
129	Coordinacion/Planificacion	50	n/r
130	Reuniones con cliente	50	n/r
131	Coordinacion/Planificacion	51	n/r
132	Reuniones con cliente	51	n/r
133	Documentacion	51	n/r
137	Coordinacion/Planificacion	53	n/r
138	Reuniones con cliente	53	n/r
139	Documentacion	53	n/r
140	Coordinacion/Planificacion	54	n/r
141	Reuniones con cliente	54	n/r
142	Diseño/Desarrollo de Software	55	n/r
146	Coordinacion/Planificacion	57	n/r
147	Reuniones con cliente	57	n/r
148	Diseño/Desarrollo de Software	57	n/r
149	Coordinacion/Planificacion	58	n/r
150	Reuniones con cliente	58	n/r
151	Diseño/Desarrollo de Software	58	n/r
152	Documentacion	58	n/r
423	Coordinacion/Planificacion	187	Gestionar tareas e hitos a cumplir en el semestre
424	Reuniones con cliente	187	Presentar organizacion semestral 
425	Documentacion	187	Desarrollar historias de usuario y epicas segun las reuniones con el cliente
431	Diseño/Desarrollo de Software	191	Inicio del desarrollo de los modelos y logicas de cotizaciones 
432	Reuniones con cliente	191	Presentacion de nueva etapa y dudas tecnicas de cotizaciones
433	Coordinacion/Planificacion	191	Generacion de quemado de tareas actualizado y coordinacion de reuniones de equipos de desarrollo
444	Coordinacion/Planificacion	196	coordinar entrega de sprint 1
445	Reuniones con cliente	196	presentar sprint 1
451	Reuniones con cliente	200	- Presentar al cliente primera versión completa del sistema.
452	Pruebas/QA	200	- Probar, internamente, el sistema completo en búsqueda de correcciones.
163	Coordinacion/Planificacion	63	n/r
164	Reuniones con cliente	63	n/r
165	Diseño/Desarrollo de Software	63	n/r
166	Diseño/Desarrollo de Software	64	n/r
167	Coordinacion/Planificacion	65	n/r
168	Reuniones con cliente	65	n/r
453	Diseño/Desarrollo de Software	200	- Integrar validaciones de parámetros, mejorar informe de impacto al eliminar registros y agregar búsquedas en las bases de precios.
174	Coordinacion/Planificacion	68	n/r
175	Reuniones con cliente	68	n/r
176	Diseño/Desarrollo de Software	68	n/r
181	Reuniones con cliente	70	n/r
182	Diseño/Desarrollo de Software	70	n/r
187	Coordinacion/Planificacion	72	n/r
188	Reuniones con cliente	72	n/r
189	Diseño/Desarrollo de Software	72	n/r
192	Coordinacion/Planificacion	74	n/r
193	Reuniones con cliente	74	n/r
194	Documentacion	74	n/r
195	Entrega/Capacitacion	74	n/r
196	Coordinacion/Planificacion	75	n/r
197	Reuniones con cliente	75	n/r
198	Diseño/Desarrollo de Software	75	n/r
199	Coordinacion/Planificacion	76	n/r
200	Reuniones con cliente	76	n/r
201	Documentacion	76	n/r
203	Coordinacion/Planificacion	78	n/r
204	Reuniones con cliente	78	n/r
205	Documentacion	78	n/r
206	Coordinacion/Planificacion	79	n/r
207	Reuniones con cliente	79	n/r
208	Diseño/Desarrollo de Software	79	n/r
209	Documentacion	79	n/r
210	Documentacion	80	n/r
211	Diseño/Desarrollo de Software	81	n/r
213	Coordinacion/Planificacion	83	n/r
214	Reuniones con cliente	83	n/r
215	Diseño/Desarrollo de Software	83	n/r
216	Documentacion	83	n/r
217	Coordinacion/Planificacion	84	n/r
218	Diseño/Desarrollo de Software	84	n/r
219	Coordinacion/Planificacion	85	n/r
220	Reuniones con cliente	85	n/r
221	Coordinacion/Planificacion	86	n/r
222	Reuniones con cliente	86	n/r
223	Documentacion	86	n/r
224	Coordinacion/Planificacion	87	n/r
225	Reuniones con cliente	87	n/r
226	Coordinacion/Planificacion	88	n/r
227	Reuniones con cliente	88	n/r
228	Documentacion	88	n/r
229	Coordinacion/Planificacion	89	n/r
230	Reuniones con cliente	89	n/r
231	Diseño/Desarrollo de Software	89	n/r
236	Coordinacion/Planificacion	91	n/r
237	Diseño/Desarrollo de Software	91	n/r
238	Coordinacion/Planificacion	92	n/r
239	Reuniones con cliente	92	n/r
240	Diseño/Desarrollo de Software	92	n/r
241	Documentacion	92	n/r
243	Reuniones con cliente	94	n/r
244	Documentacion	94	n/r
248	Coordinacion/Planificacion	96	n/r
249	Reuniones con cliente	96	n/r
250	Diseño/Desarrollo de Software	96	n/r
251	Coordinacion/Planificacion	97	n/r
252	Reuniones con cliente	97	n/r
253	Diseño/Desarrollo de Software	97	n/r
254	Diseño/Desarrollo de Software	98	n/r
255	Diseño/Desarrollo de Software	99	n/r
256	Coordinacion/Planificacion	100	n/r
257	Diseño/Desarrollo de Software	100	n/r
258	Documentacion	100	n/r
426	Diseño/Desarrollo de Software	188	Implementacion de autenticacion de roles.
260	Coordinacion/Planificacion	102	n/r
261	Reuniones con cliente	102	n/r
262	Diseño/Desarrollo de Software	102	n/r
434	Diseño/Desarrollo de Software	192	Desarrollo de logica de cotizaciones 
435	Reuniones con cliente	192	Muestra de avances y dudas tecnicas sobre flujos de cotizaciones
436	Reuniones con cliente	193	Muestra de version incial del producto
437	Diseño/Desarrollo de Software	193	Desarrollo de logica de cotizaciones 
438	Pruebas/QA	193	Revision de flujos  de cotizaciones en funcion al Excel proporcionado
439	Instalaciones/Despliegue	193	Primer despliegue en cloud de toda la infraestructura
446	Coordinacion/Planificacion	197	Organizar el proyecto según las necesidades del cliente.
447	Reuniones con cliente	197	Recopilar y acordar las cosas y procesos necesarios para poder desarrollar el proyecto a lo largo del semestre.
281	Reuniones con cliente	110	n/r
282	Diseño/Desarrollo de Software	110	n/r
284	Coordinacion/Planificacion	112	n/r
285	Reuniones con cliente	112	n/r
286	Diseño/Desarrollo de Software	112	n/r
287	Documentacion	112	n/r
288	Diseño/Desarrollo de Software	113	n/r
289	Diseño/Desarrollo de Software	114	n/r
294	Diseño/Desarrollo de Software	116	n/r
295	Diseño/Desarrollo de Software	117	n/r
297	Diseño/Desarrollo de Software	119	n/r
298	Coordinacion/Planificacion	120	n/r
299	Diseño/Desarrollo de Software	120	n/r
302	Coordinacion/Planificacion	122	n/r
303	Reuniones con cliente	122	n/r
304	Diseño/Desarrollo de Software	122	n/r
307	Coordinacion/Planificacion	124	n/r
308	Diseño/Desarrollo de Software	124	n/r
309	Documentacion	124	n/r
310	Coordinacion/Planificacion	125	n/r
311	Reuniones con cliente	125	n/r
312	Diseño/Desarrollo de Software	125	n/r
313	Coordinacion/Planificacion	126	n/r
314	Reuniones con cliente	126	n/r
315	Diseño/Desarrollo de Software	126	n/r
316	Coordinacion/Planificacion	127	n/r
317	Reuniones con cliente	127	n/r
318	Diseño/Desarrollo de Software	127	n/r
319	Coordinacion/Planificacion	128	n/r
320	Reuniones con cliente	128	n/r
321	Diseño/Desarrollo de Software	128	n/r
322	Documentacion	128	n/r
330	Diseño/Desarrollo de Software	132	n/r
331	Diseño/Desarrollo de Software	133	n/r
332	Diseño/Desarrollo de Software	134	n/r
337	Diseño/Desarrollo de Software	138	n/r
339	Coordinacion/Planificacion	140	n/r
340	Reuniones con cliente	140	n/r
341	Diseño/Desarrollo de Software	140	n/r
345	Reuniones con cliente	142	n/r
346	Diseño/Desarrollo de Software	142	n/r
347	Coordinacion/Planificacion	143	n/r
348	Reuniones con cliente	143	n/r
349	Documentacion	143	n/r
353	Diseño/Desarrollo de Software	145	n/r
427	Reuniones con cliente	189	Muestra de avances y dudas tecnicas de cotizaciones 
428	Documentacion	189	Descripcion de los flujos del negocio
357	Coordinacion/Planificacion	147	n/r
358	Reuniones con cliente	147	n/r
359	Coordinacion/Planificacion	148	n/r
360	Diseño/Desarrollo de Software	148	n/r
361	Diseño/Desarrollo de Software	149	n/r
362	Diseño/Desarrollo de Software	150	n/r
363	Pruebas/QA	150	n/r
364	Coordinacion/Planificacion	151	n/r
365	Diseño/Desarrollo de Software	151	n/r
366	Coordinacion/Planificacion	152	n/r
367	Diseño/Desarrollo de Software	152	n/r
368	Coordinacion/Planificacion	153	n/r
369	Diseño/Desarrollo de Software	153	n/r
370	Diseño/Desarrollo de Software	154	n/r
371	Reuniones con cliente	155	n/r
372	Pruebas/QA	155	n/r
373	Diseño/Desarrollo de Software	156	n/r
440	Coordinacion/Planificacion	194	Seguir planificando las cosas a hacer y las próximas reuniones con el cliente
441	Reuniones con cliente	194	seguir entendiendo su negocio y resolver dudas
376	Coordinacion/Planificacion	158	n/r
377	Reuniones con cliente	158	n/r
378	Diseño/Desarrollo de Software	158	n/r
448	Diseño/Desarrollo de Software	198	Continuar con desarrollo en backend y frontend.
380	Diseño/Desarrollo de Software	160	n/r
381	Diseño/Desarrollo de Software	161	n/r
382	Diseño/Desarrollo de Software	162	n/r
385	Diseño/Desarrollo de Software	165	n/r
389	Reuniones con cliente	167	n/r
390	Diseño/Desarrollo de Software	167	n/r
394	Reuniones con cliente	169	n/r
395	Diseño/Desarrollo de Software	169	n/r
396	Diseño/Desarrollo de Software	170	n/r
397	Diseño/Desarrollo de Software	171	n/r
398	Diseño/Desarrollo de Software	172	n/r
399	Diseño/Desarrollo de Software	173	n/r
400	Coordinacion/Planificacion	174	n/r
401	Diseño/Desarrollo de Software	174	n/r
402	Coordinacion/Planificacion	175	n/r
403	Diseño/Desarrollo de Software	175	n/r
405	Documentacion	177	n/r
406	Coordinacion/Planificacion	178	n/r
407	Reuniones con cliente	178	n/r
408	Otros	178	n/r
409	Pruebas/QA	178	n/r
410	Documentacion	178	n/r
411	Diseño/Desarrollo de Software	179	n/r
412	Diseño/Desarrollo de Software	180	n/r
419	Diseño/Desarrollo de Software	183	n/r
420	Pruebas/QA	184	Viendo si sirve desde móvil
\.


--
-- Data for Name: helper; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.helper (id, email, name, password, id_teacher) FROM stdin;
1	ayudante.saez@usach.cl	Ayudante Saez (Ayudante)	test1234	1
\.


--
-- Data for Name: proyect; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyect (id, code, name, id_section) FROM stdin;
1	P80	Proyecto-test	1
2	P01	Proyecto 1	2
3	P02	Proyecto 2	2
5	P06	Floreria	1
6	P02	Avance Semanal	1
7	P12	ASTRO	1
4	P99	Proyecto 99 - probando nombre	2
14	P04	Mundo Neurodiferente	4
16	P09	Kim Pets	4
17	P10	Geo Ingenieria Geomática	4
18	P03	Pastelería Doña Emilia	4
20	P08	Termopanel System	4
21	P13	Dulce Imperio	4
19	P16	HUAP - Gestion de Turnos v2	4
15	P15	HUAP - Normalizac. datos HDOM	4
\.


--
-- Data for Name: section; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.section (id, finish_date, is_active, section_code, semester, start_date, year, id_teacher) FROM stdin;
1	2026-08-01	t	prueba-seccion-256	1	2026-03-30	2026	1
2	2026-08-03	t	Seccion A - 1-2026 (prueba)	1	2026-03-30	2026	3
4	2026-08-30	t	2026-1 seccion-A	1	2026-03-29	2026	3
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student (id, email, lastname, name, id_section, id_proyect) FROM stdin;
19	alumno.10@usach.cl	10	Alumno	1	\N
21	alumno.12@usach.cl	12	Alumno	1	\N
25	alumno.16@usach.cl	16	Alumno	1	\N
27	alumno.18@usach.cl	18	Alumno	1	\N
28	alumno.19@usach.cl	19	Alumno	1	\N
29	alumno.20@usach.cl	20	Alumno	1	\N
30	alumno.21@usach.cl	21	Alumno	1	\N
32	alumno.23@usach.cl	23	Alumno	1	\N
34	alumno.25@usach.cl	25	Alumno	1	\N
35	alumno.26@usach.cl	26	Alumno	1	\N
36	alumno.27@usach.cl	27	Alumno	1	\N
37	alumno.28@usach.cl	28	Alumno	1	\N
43	alumno.34@usach.cl	34	Alumno	1	\N
44	alumno.35@usach.cl	35	Alumno	1	\N
45	alumno.36@usach.cl	36	Alumno	1	\N
46	alumno.37@usach.cl	37	Alumno	1	\N
47	alumno.38@usach.cl	38	Alumno	1	\N
48	alumno.39@usach.cl	39	Alumno	1	\N
49	alumno.40@usach.cl	40	Alumno	1	\N
11	alumno.2@usach.cl	2	Alumno	1	5
23	alumno.14@usach.cl	14	Alumno	1	5
24	alumno.15@usach.cl	15	Alumno	1	5
26	alumno.17@usach.cl	17	Alumno	1	5
10	alumno.1@usach.cl	1	Alumno	1	1
12	alumno.3@usach.cl	3	Alumno	1	1
16	alumno.7@usach.cl	7	Alumno	1	1
17	alumno.8@usach.cl	8	Alumno	1	1
13	alumno.4@usach.cl	4	Alumno	1	\N
14	alumno.5@usach.cl	5	Alumno	1	\N
18	alumno.9@usach.cl	9	Alumno	1	6
38	alumno.29@usach.cl	29	Alumno	1	6
39	alumno.30@usach.cl	30	Alumno	1	6
41	alumno.32@usach.cl	32	Alumno	1	6
42	alumno.33@usach.cl	33	Alumno	1	6
40	alumno.31@usach.cl	31	Alumno	1	\N
15	alumno.6@usach.cl	6	Alumno	1	7
20	alumno.11@usach.cl	11	Alumno	1	7
22	alumno.13@usach.cl	13	Alumno	1	7
31	alumno.22@usach.cl	22	Alumno	1	7
33	alumno.24@usach.cl	24	Alumno	1	7
50	otro.alumno@usach.cl	Alumno	Otro	2	2
51	alumno.dos@usach.cl	Dos	Alumno	2	3
52	alumna.tres@usach.cl	Tres	Alumna	2	3
1	alumno.dummy@usach.cl	Dummy	Alumno	2	2
53	ultimo.alumno@usach.cl	Alumno	ElUltimo	2	4
54	alumno_mas.uno@usach.cl	Uno	Alumno_mas	2	\N
55	alumno_mas.dos@usach.cl	Dos	Alumno_mas	2	\N
56	alumno_mas.tres@usach.cl	Tres	Alumno_mas	2	\N
57	alumno_mas.cuatro@usach.cl	Cuatro	Alumno_mas	2	\N
58	alumno_mas.cinco@usach.cl	Cinco	Alumno_mas	2	\N
77	felipe.cubillos.a@usach.cl	Cubillos	Felipe	4	14
79	fabian.lizama@usach.cl	Lizama	Fabian	4	16
80	amaru.monje@usach.cl	Monje	Amaru	4	17
81	sebastian.tapia.ga@usach.cl	Tapia	Sebastian	4	16
82	andrea.cosio@usach.cl	Cosio	Andrea	4	17
83	cesar.rodriguez.pa@usach.cl	Rodriguez	Cesar	4	18
84	sara.salas@usach.cl	Salas	Sara	4	16
85	gabriel.cabrera.q@usach.cl	Cabrera	Gabriel	4	18
86	nicolas.garcia.r@usach.cl	Garcia	Nicolas	4	18
87	thomas.gustafsson@usach.cl	Gustafsson	Thomas	4	16
88	alonso.henriquez.h@usach.cl	Henriquez	Alonso	4	19
89	braulio.bravo.c@usach.cl	Bravo	Braulio	4	19
90	diego.molina.a@usach.cl	Molina	Diego	4	19
91	benjamin.bustamante@usach.cl	Bustamante	Benjamin	4	15
92	giuseppe.cavallieri@usach.cl	Cavallieri	Giuseppe	4	19
93	mohamed.al-marzuk@usach.cl	Al-marzuk	Mohamed	4	17
94	nicolas.morales.r@usach.cl	Morales	Nicolas	4	17
95	benjamin.moya.m@usach.cl	Moya	Benjamin	4	20
96	ignacio.celis@usach.cl	Celis	Ignacio	4	20
97	juan.loyola@usach.cl	Loyola	Juan	4	20
98	tomas.carcamo.g@usach.cl	Carcamo	Tomas	4	21
99	camila.lagos.l@usach.cl	Lagos	Camila	4	20
100	duvan.vergara@usach.cl	Vergara	Duvan	4	15
101	francisco.riquelme.n@usach.cl	Riquelme	Francisco	4	20
102	agustin.saavedra@usach.cl	Saavedra	Agustin	4	14
103	sofia.gacitua@usach.cl	Gacitua	Sofia	4	14
104	martin.salinas.v@usach.cl	Salinas	Martin	4	19
105	diego.gomez.g@usach.cl	Gomez	Diego	4	14
106	thomas.riffo@usach.cl	Riffo	Thomas	4	21
107	benjamin.sepulveda@usach.cl	Sepulveda	Benjamin	4	15
108	ignacio.solar@usach.cl	Solar	Ignacio	4	15
109	sebastian.cassone@usach.cl	Cassone	Sebastian	4	18
110	patricio.briceno@usach.cl	Briceno	Patricio	4	17
78	alan.berrios@usach.cl	Berrios	Alan	4	\N
\.


--
-- Data for Name: teacher; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teacher (id, email, name, password) FROM stdin;
3	alvaro.yanez@usach.cl	Alvaro Yañez	ayc2026-1
1	omar.saez@usach.cl	Omar Saez	test1234
4	carolina.bonacic@usach.cl	Carolina Bonacic	carolina123
\.


--
-- Name: advance_detail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advance_detail_id_seq', 658, true);


--
-- Name: advance_future_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advance_future_id_seq', 453, true);


--
-- Name: advance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advance_id_seq', 200, true);


--
-- Name: helper_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.helper_id_seq', 1, true);


--
-- Name: proyect_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proyect_id_seq', 21, true);


--
-- Name: section_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.section_id_seq', 4, true);


--
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_id_seq', 110, true);


--
-- Name: teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teacher_id_seq', 4, true);


--
-- Name: advance_detail advance_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance_detail
    ADD CONSTRAINT advance_detail_pkey PRIMARY KEY (id);


--
-- Name: advance_future advance_future_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance_future
    ADD CONSTRAINT advance_future_pkey PRIMARY KEY (id);


--
-- Name: advance advance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance
    ADD CONSTRAINT advance_pkey PRIMARY KEY (id);


--
-- Name: helper helper_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.helper
    ADD CONSTRAINT helper_pkey PRIMARY KEY (id);


--
-- Name: proyect proyect_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyect
    ADD CONSTRAINT proyect_pkey PRIMARY KEY (id);


--
-- Name: section section_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.section
    ADD CONSTRAINT section_pkey PRIMARY KEY (id);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);


--
-- Name: teacher uk3kv6k1e64a9gylvkn3gnghc2q; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT uk3kv6k1e64a9gylvkn3gnghc2q UNIQUE (email);


--
-- Name: helper uk5ltkpqawr0jbrqoip61swpwqe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.helper
    ADD CONSTRAINT uk5ltkpqawr0jbrqoip61swpwqe UNIQUE (email);


--
-- Name: student fk27i7qt7avugit2nfyybfvdtpa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fk27i7qt7avugit2nfyybfvdtpa FOREIGN KEY (id_proyect) REFERENCES public.proyect(id);


--
-- Name: advance_future fk3kg1a0tmkg4nbciaxwlo26n2o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance_future
    ADD CONSTRAINT fk3kg1a0tmkg4nbciaxwlo26n2o FOREIGN KEY (id_advance) REFERENCES public.advance(id);


--
-- Name: helper fka7ireq1ux47iycwvm1pqdgyse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.helper
    ADD CONSTRAINT fka7ireq1ux47iycwvm1pqdgyse FOREIGN KEY (id_teacher) REFERENCES public.teacher(id);


--
-- Name: student fkdgb3t2qt696j034s8svf8iptw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkdgb3t2qt696j034s8svf8iptw FOREIGN KEY (id_section) REFERENCES public.section(id);


--
-- Name: advance fkmvs7d83j94f4ldrwrf0v2cg9u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance
    ADD CONSTRAINT fkmvs7d83j94f4ldrwrf0v2cg9u FOREIGN KEY (id_proyect) REFERENCES public.proyect(id);


--
-- Name: section fkojm9s9a7yh7f3lemp5k1x7u4v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.section
    ADD CONSTRAINT fkojm9s9a7yh7f3lemp5k1x7u4v FOREIGN KEY (id_teacher) REFERENCES public.teacher(id);


--
-- Name: proyect fkq9yg7e1gm2772wapuf39ata0p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyect
    ADD CONSTRAINT fkq9yg7e1gm2772wapuf39ata0p FOREIGN KEY (id_section) REFERENCES public.section(id);


--
-- Name: advance_detail fkqbwadrh73r6luj6gmm3ts9aun; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance_detail
    ADD CONSTRAINT fkqbwadrh73r6luj6gmm3ts9aun FOREIGN KEY (id_advance) REFERENCES public.advance(id);


--
-- Name: advance fkt5lxbq8qicmhf4y5nc2j24qxr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advance
    ADD CONSTRAINT fkt5lxbq8qicmhf4y5nc2j24qxr FOREIGN KEY (id_student) REFERENCES public.student(id);


--
-- PostgreSQL database dump complete
--

\unrestrict WNamaXOxEsQl9qkJmSSYA8BCgIsTV8BPMcDp3eOgdtoe7WX6cnYHZKEQcfHofQe

